name: Build Alpine Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      options: --privileged

    steps:
      - name: Install build dependencies
        run: |
          apk update
          apk add alpine-sdk sudo bash git cmake build-base ninja linux-headers

          adduser -D -G abuild builder
          echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          chown: true

      - name: Setup abuild keys
        env:
          APKBUILD_PUBKEY: ${{ secrets.APKBUILD_PUBKEY }}
          APKBUILD_PRIKEY: ${{ secrets.APKBUILD_PRIKEY }}
        run: |
          mkdir -p /home/builder/.abuild

          echo "$APKBUILD_PUBKEY" > /home/builder/.abuild/product.rsa.pub
          chmod 600 /home/builder/.abuild/product.rsa.pub
          echo "$APKBUILD_PRIKEY" > /home/builder/.abuild/product.rsa
          chmod 600 /home/builder/.abuild/product.rsa

          echo "PACKAGER_PRIVKEY=\"/home/builder/.abuild/product.rsa\"" > /home/builder/.abuild/abuild.conf
          chown -R builder:abuild /home/builder/

      - name: Update APKBUILD and Build
        run: |
          cd package


          VERSION="${{ github.ref_name }}"
          
          sed -i "s/^pkgver=.*/pkgver=$VERSION/" APKBUILD

          chown -R builder:abuild .


          su builder -c "abuild checksum"
          su builder -c "abuild unpack"
          (cd src/relayd-alpine-1.0.0/src && git clone https://github.com/openwrt/libubox.git)
          su builder -c "abuild build"

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: alpine-packages
          path: /home/builder/packages/**/*.apk
